# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       libprofile-qt5

# >> macros
# << macros

Summary:    Qt5 library for profiles
Version:    0.34.0.4
Release:    1
Group:      System/System Control
License:    LGPLv2.1
URL:        http://github.com/nemomobile/libprofile-qt
Source0:    %{name}-%{version}.tar.bz2
Requires:   profiled
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  doxygen

%description
Qt5 wrapper library for profiles

%package -n libprofile-qt5-devel
Summary:    Development headers for libprofile-qt5 library
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   pkgconfig(Qt5Core)
Requires:   libprofile-qt5 = %{version}

%description -n libprofile-qt5-devel
Development headers for libprofile-qt5 library


%package -n libprofile-qt5-tests
Summary:    Unit tests for libprofile-qt5
Group:      Development/System
Requires:   %{name} = %{version}-%{release}
Requires:   libprofile-qt5 = %{version}

%description -n libprofile-qt5-tests
Unit tests for libprofile-qt5


%package -n libprofile-qt5-doc
Summary:    API documentation for libprofile-qt5
Group:      Documentation
BuildArch:  noarch
Requires:   %{name} = %{version}-%{release}

%description -n libprofile-qt5-doc
API documentation for libprofile-qt5


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%{_libdir}/libprofile-qt5.so.*
# >> files
# << files

%files -n libprofile-qt5-devel
%defattr(-,root,root,-)
%{_libdir}/libprofile-qt5.so
%{_includedir}/profile-qt5/Profile
%{_includedir}/profile-qt5/profile.h
# >> files libprofile-qt5-devel
# << files libprofile-qt5-devel

%files -n libprofile-qt5-tests
%defattr(-,root,root,-)
%{_libdir}/libprofile-qt5-tests/ut_profile
%{_datadir}/libprofile-qt5-tests/tests.xml
# >> files libprofile-qt5-tests
# << files libprofile-qt5-tests

%files -n libprofile-qt5-doc
%defattr(-,root,root,-)
%{_docdir}/libprofile-qt5/*
# >> files libprofile-qt5-doc
# << files libprofile-qt5-doc
